### ISSUE TITLE
Getting strange text in the editor

### ISSUE THREAD

**Issue by learning-91** [django-ace/django-ace#13]
I am getting this value in the editor:
`
ההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההההXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

\
I have the following code in JS:
```javascript
var editor = ace.edit("editor");
editor.session.setMode("ace/mode/json")
        editor.setOptions({
            mode: "json",
            wrap: true,
        });
```

If I remove these lines, nothing is added in the editor. How can I solve this issue?

**Comment by JulienPalard** [comment]
Hi! For the moment I have no idea, but let's start with simple things:
I just release django-ace 1.0.6, with ACE bumped from 1.4.2 to 1.4.7, can you try it?

**Comment by JulienPalard** [comment]
I'm closing this, as I'm missing informations, don't hesitate to repoen as needed.
