### ISSUE TITLE
License incorrectly references MPL/LGPL/GPL

### ISSUE THREAD

**Issue by SamuelMS** [django-ace/django-ace#16]
The `LICENSE` references an extremely old tri-license (MPL/LGPL/GPL) from Ace `0.2.0`, but this library packages version `1.4.8`. Ace changed their license to BSD **eight years ago**: https://github.com/ajaxorg/ace/blob/master/LICENSE

Our organization is unable to use this library until the `LICENSE` file properly reflects Ace's BSD license and drops the reference to version `0.2.0`.

Happy to submit a PR to change this.

**Comment by JulienPalard** [comment]
Fixed! Thanks for noticing :)
