### ISSUE TITLE
JavaScript Error because of incorrect mime type for static file

### ISSUE THREAD

**Issue by meena-erian** [django-ace/django-ace#19]
Python 3.9.5
Django v3.2.4
django_ace v1.0.11

JavaScript error:
```
Refused to execute script from 'http://127.0.0.1:8000/static/django_ace/ace/worker-json.js' because its MIME type ('text/plain') is not executable.

Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://127.0.0.1:8000/static/django_ace/ace/worker-json.js' failed to load.
```

**Comment by JulienPalard** [comment]
Hi @meena-erian, I can't reproduce your issue:

neither in dev:
```
$ curl -I localhost:8000/static/django_ace/ace/worker-json.js
HTTP/1.1 200 OK
Content-Type: application/javascript
```
or in prod:
```
$ curl -I https://www.hackinscience.org/static/django_ace/ace/worker-json.js 
HTTP/2 200 
server: nginx/1.14.2
date: Wed, 02 Jun 2021 16:11:13 GMT
content-type: application/javascript
```

How are you serving your assets?

**Comment by meena-erian** [comment]
Hi @JulienPalard Thank you for following up!

Actually, same!

I'm unable to reproduce it myself on any other device, yet it's persistent on my server regardless of whether the development mode is set to `True` or `False` and regardless of any configurations of my Django app ( I tried creating new blank projects using `django-admin startproject` and the error still shows up)

I suspect it has to do with a specific version of a required package. so here are the results of `pip list` on the server that show the problem.

```
Package            Version
------------------ ---------
asgiref            3.3.4    
autopep8           1.5.7    
bleach             3.3.0    
certifi            2021.5.30
cffi               1.14.5   
chardet            4.0.0    
colorama           0.4.4    
cryptography       3.4.7    
Django             3.2.3    
django-ace         1.0.11   
django-pdr         0.1      
django-pgcrypto    2.0.0
docutils           0.17.1
greenlet           1.1.0
idna               2.10
importlib-metadata 4.4.0
keyring            23.0.1
packaging          20.9
pip                21.1.1
pkginfo            1.7.0
psycopg2           2.8.6
pycodestyle        2.7.0
pycparser          2.20
Pygments           2.9.0
pyparsing          2.4.7
pytz               2021.1
pywin32-ctypes     0.2.0
readme-renderer    29.0
requests           2.25.1
requests-toolbelt  0.9.1
rfc3986            1.5.0
setuptools         56.0.0
six                1.16.0
sqlalchemy         1.4.17
sqlparse           0.4.1
toml               0.10.2
tqdm               4.61.0
twine              3.4.1
urllib3            1.26.5
webencodings       0.5.1
wheel              0.36.2
zipp               3.4.1
```

I'll do further investigation and I'll update you as soon as possible.

**Comment by JulienPalard** [comment]
> on my server

Do you serve static files using an HTTP server, bypassing Django, after a `./manage.py collectstatic`?

If not, you should.

if so it's the goal of the web server, not Django, to tell the content type, as Django is bypassed, and the issue can't depend on the Python package installed, as no Python should be involved serving those files.

Are you using nginx? Do you have the `include /etc/nginx/mime.types` in your config?

**Comment by meena-erian** [comment]
For now, I'm serving static files using Django. It's very confusing that the error shows only for this file but I think you're right! It's very unlikely to have anything to do with Django or the django_ace package. 

Please forgive me for the inconvenience

**Comment by JulienPalard** [comment]
> Please forgive me for the inconvenience

Don't worry ☺ if you finally find out please let me know, it may help someone later.
