### ISSUE TITLE
WARNING django.request: Not Found: worker-html.js

### ISSUE THREAD

**Issue by Archmonger** [django-ace/django-ace#21]
Currently getting some errors when utilizing django-ace in an iframe.

```py
WARNING django.request: Not Found: /iframe/worker-html.js
```

Note: I don't _think_ this is directly caused by `django-ace` being in an iframe, but I thought I'd mention it.

Additionally, `django-ace` seems to behave perfectly fine even with this error being present.

Here is my `AceWidget`

```python
    head_html = CharField(
        widget=AceWidget(
            mode="html",
            theme="twilight",
            width="100%",
            toolbar=False,
            showprintmargin=False,
        ),
        label="Custom HTML (head)",
        required=False,
    )
```

**Comment by Archmonger** [comment]
Seems to be specifically related to Django `collectstatic` (with `DEBUG=False`).

When `DEBUG=True` I get the following
```python
INFO django.channels.server: HTTP GET /static/django_ace/ace/worker-html.js 304 [0.00, 127.0.0.1:52312]
```

Here's some relevant snippets of my Django staticfiles settings

```python
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
]
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
```

**Comment by JulienPalard** [comment]
I can't reproduce your issue yet. Looks like on hackinscience (the site on which I use django-ace), the collect static collects the file:

=> https://www.hackinscience.org/static/django_ace/ace/worker-html.js

What is strange is `/iframe/worker-html.js`, it should be `/.../django_ace/ace/worker-html.js`.

Can you share a reproducer, or at least the HTML code generated querying worker-html.js?

**Comment by Archmonger** [comment]
Currently reproduceable on [conreq@app-store](https://github.com/Archmonger/Conreq/tree/app_store). Dependencies are all pip installable. 

`DEBUG` needs to be off, and you need to open the tab `Server Settings > Styling`

**Comment by Archmonger** [comment]
Also I've verified `collectstatic` is in fact collecting `worker-html.js`.

It's simply the link itself within the page which is pointing to the wrong URL.

**Comment by JulienPalard** [comment]
Looks like I havent took the time to look at it (my front-end skills are not motivating me here...), have you found a fix?

**Comment by Archmonger** [comment]
Nope. It's not a breaking bug so I've just been ignoring it.
